### ISSUE TITLE
Rename repo to alexa_media or alexa_media_player?

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#107]
@keatontaylor do you think we should rename this repo to `alexa_media_player` or `alexa_media` so it's more descriptive?  For straight repo renames, GitHub does do redirects so in theory links in git and elsewhere won't break (unless you recreate `custom_components` I'd guess).

This is entirely an [owner setting](https://help.github.com/en/articles/renaming-a-repository) so feel free to just do it or close this issue and stick with the current repo name.

**Comment by brianhanifin** [comment]
I can confirm that repo renames work the way @alandtse says. I renamed my Home-AssistantConfig to Home-Assistant-Config and old links from the forums seem to still go to my config.

**Comment by keatontaylor** [comment]
Done
