### ISSUE TITLE
does not work after update to 0.89.1

### ISSUE THREAD

**Issue by papperone** [keatontaylor/alexa_media_player#109]
as per title, component was working perfectily until 1h ago with 0.89.0 but after update to the latest 0.89.1 I've message that component cannot setup and this in the HA log:

Error during setup of component alexa_media
15:21 deps/lib/python3.7/site-packages/alexapy/alexalogin.py (ERROR)

**Comment by Segfault198** [comment]
Custom components changed in 0.89, gonna need to give them some time to rework the code.
https://www.home-assistant.io/blog/2019/03/06/release-89/

**Comment by papperone** [comment]
ok thanks for reply... weirdly with 0.89 it was working in my installation... it broke now that I update to 0.89.1

**Comment by chali272** [comment]
it is working perfectly in my installation?  using hass.io (docker) 0.89.1

**Comment by Segfault198** [comment]
Its throwing errors on mine (Virtenv) but I chocked them up to the component changes so I didn't dig too deeply.

**Comment by alandtse** [comment]
The component changes were preemptively addressed in 1.1.0.  Please [update to the latest version](https://github.com/keatontaylor/alexa_media_player/wiki/Configuration#versions--100). We will not be supporting anything in the 0.x.y branch moving forward.

Assuming that was completed successfully, if you're seeing errors, we'll need logs to debug it.  Please also identify:

1. HA version
2. alexa_media version
3. alexapy version

**Comment by papperone** [comment]
I had already update to 1.1.0 when I used 0.88 and it worked flowlessly until 0.89.2....
After this last update I've the error I reported here and component does not work:

Error during setup of component alexa_media
15:21 deps/lib/python3.7/site-packages/alexapy/alexalogin.py (ERROR)

and after boot I've a persisten notification in HA:
![immagine](https://user-images.githubusercontent.com/28104633/54103915-69de2180-43ce-11e9-925d-b41b9ae55db0.png)

still pending solution then....

**Comment by alandtse** [comment]
Please generate [some logs for alexapy](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) and identify the version of alexapy by looking at the [__version__.py file](https://gitlab.com/keatontaylor/alexapy/blob/master/alexapy/__version__.py)..

**Comment by ehendrix23** [comment]
FYI,

I just updated to 0.89.1 (I was still on like 0.86.x); and also updated alexa to what seems to be 1.2.0 (based on __version__ in __init__.py) and it is working.

Know that it does not mean cause it works for me it works for everyone <g>, but figured to give this little bit of info here.

**Comment by krissen** [comment]
Two more cents, as I had appreciated more user reports in this thread earlier. Decided to take the plunge yesterday, and updated HA to 0.89.1 (from 0.88.2). alexa_media_player 1.1.0 worked without a hitch, and has kept working since (across reboots etc. for unrelated reasons).

**Comment by papperone** [comment]
sorry for delay in update, I did restore snapshot took before 0.89.1 update, I verified Alexa Custom Component was wrokgin then I update again to 0.89.1 and now all is working....
only the custom updater is not recognizing the component despite I follow the instructions on the Wiki, any clue or I need to open a different Issue tracker??

**Comment by alandtse** [comment]
@papperone I'll close this for now. 

For custom_updater, I can only provide a little bit of support since it's not my code.  Please check the [url in the wiki](https://github.com/keatontaylor/alexa_media_player/wiki#custom_updater-versions--110) for configuring it as it has changed.

The Wiki lists both a dev and a production version. You **only need** the production url. If it still doesn't work, we please open a new issue to discuss.
