### ISSUE TITLE
Functionality Question

### ISSUE THREAD

**Issue by seaverd** [keatontaylor/alexa_media_player#116]
I have this custom component installed...current version 1.2 along with alexapy 0.3.  On the version <1.0 I was able to tell my echo to set an alarm for 6am the following morning and I have a nodered flow setup so that when I hit a button next to my bed it kicks off our morning routine.  

One of the items in the routine is to send via the call service node with the nodered ha websockets palette (version 0.9.1) media_player turn_off media_player.echo1 under the current version it does not stop the alarm.  

Any suggestions on how to troubleshoot this.  

In general the cover art and media player controls within home assistant are not working for me right away.  If I wait several minutes coverart then updates and I can pause via home assistant media player UI.  

Likewise in my testing of nodered, if I use that to toggle my echo on....using my morning routine I am able to turn off the echo...so I know my node is configured correctly.  That's why I am asking the question...does this component only work if the calls to initiate the music and alarm are via this component?

**Comment by alandtse** [comment]
The Media Player will stop updating after it detects the devices are idle.  It will only begin updating again if commands are issued through this component. Any interaction outside of this component, other than using a voice command, will not result in the Media Player updating. This was to avoid having the component continuously contact Amazon 24/7 and potentially cause a ban.

That said, any commands through this component for a specific Echo device should result in that being rechecked to see if it's playing and then the updating will continue as long as the device is playing.

FYI, please use paragraph breaks so it's easier to understand your question. I added it in for you so I could understand this.
