### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_job'

### ISSUE THREAD

**Issue by adamnmcc** [keatontaylor/alexa_media_player#122]
i get the following error in the logs. 

`2019-03-13 19:44:04 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/alexa_media/media_player.py", line 179, in _handle_event

    self.schedule_update_ha_state(force_refresh=True)

  File "/usr/src/app/homeassistant/helpers/entity.py", line 316, in schedule_update_ha_state

    self.hass.add_job(self.async_update_ha_state(force_refresh))

AttributeError: 'NoneType' object has no attribute 'add_job'
`

**Comment by adamnmcc** [comment]
forcing pip3 install requests==2.14.2 inside my docker container fixed the issue though.

**Comment by alandtse** [comment]
Interesting. If you've resolved it with a new requests than I think there's a bug somewhere else that may be hard to track unless it comes back.  The error is literally saying it can't find a hass object, which should always be there as long as the component entity is setup correctly.   If it isn't setup correctly, then there's probably an error further up in the logs.

I'll leave this open for a few days to see if anyone else reports it. I've seen this in my test environment, but only if something else breaks earlier.

**Comment by alandtse** [comment]
Closing, but if anyone sees this, please reopen.
