### ISSUE TITLE
Websocket times out after period of time

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#128]
We aren't sending a websocket ping so the websocket eventually times out.

Two needed solutions:

1. Send pings
2. Graceful fallback to polling on loss of websocket

**Comment by keatontaylor** [comment]
@alandtse ping can be easily implemented. I can add this today.

**Comment by alandtse** [comment]
Great. Please note that due to pylint fixes it may be easier to start from the master branch.

**Comment by keatontaylor** [comment]
Eh, I'd probably be interested in dropping pylint in favor of:

- pydocstyle
- mypy
- flake8

**Comment by alandtse** [comment]
I don't have a strong feeling either way. If you'd prefer to go to mypy we can swap over.

**Comment by alandtse** [comment]
FYI, I added some code to handle the second issue, graceful fallbacks. It required allowing for an error and close callback.

[alexapy](https://gitlab.com/alandtse/alexapy/commits/websocket)
[alexa_media_player](https://github.com/alandtse/alexa_media_player/tree/websocket)

I am testing this now to make sure it does try to reconnect. 
My biggest concern is there should be a better way to reinitialize the websocket_client object so it reconnects.  I thought the loop forever command was supposed to handle reconnects, but it didn't overnight.

Right now, my current code creates a new object [which may leave an orphaned thread](https://gitlab.com/alandtse/alexapy/blob/websocket/alexapy/alexawebsocket.py#L64). My threading in python is rusty so if you see a fix, please let me know.

**Comment by alandtse** [comment]
Do you think the ping is different than what websocket_client has?
```python
        self.websocket.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE},
                                   ping_interval=600,
                                   ping_timeout=30)
```

**Comment by keatontaylor** [comment]
@alandtse I'll take a look.

**Comment by keatontaylor** [comment]
Looks like it indeed works out of the box with proper configuration. The alexa.amazon.com website seems to be 

> Do you think the ping is different than what websocket_client has?
> 
> ```python
>         self.websocket.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE},
>                                    ping_interval=600,
>                                    ping_timeout=30)
> ```

Looks to work with these settings out of box. Looking into how frequently https://alexa.amazon.com sends pings now.

**Comment by keatontaylor** [comment]
@alandtse Added ping/pong and created MR to master, review, approve, merge plz. 

Also I'd feel more conformable having code reviewed before going to master in either repo, I'd happily review it, but if I am not around feel free to merge without me.

**Comment by alandtse** [comment]
No problem. How much time do you want for review before I merge it in? 

I know you've had periods where you weren't as available so I've been merging it in when I thought the merges were minor.  Evidently, websockets wasn't as minor as I thought.

**Comment by keatontaylor** [comment]
No worries, give me 48 hours usually, I should be much more free. At work we finally released the product I've been working on. (Yay!)
