### ISSUE TITLE
WebSocket Error after upgrade to Ver. 1.2.2

### ISSUE THREAD

**Issue by hmmkash** [keatontaylor/alexa_media_player#129]
Hi,
after upgrading to ver 1.2.2 I have got the following error, the component was working fine with the ver 1.2.1.
```
error from callback <bound method WebsocketEchoClient.on_close of <WebsocketEchoClient(Thread-3, initial daemon)>>: on_close() takes 1 positional argument but 2 were given
```

**Comment by hmmkash** [comment]
Done!! updating alexapy
Thanks

**Comment by alandtse** [comment]
I assume you mean to say you solved it by updating alexapy right? 

The error you got is because you had an old version of websocket_client.

I'll close it then.

**Comment by hmmkash** [comment]
Yes solved after updating alexapy.
Thanks

**Comment by Obicom** [comment]
Please apologize the stupid question .. but alexapy can be updated by me (or others)? Or will it be implemented with next alexa media player update?

**Comment by hmmkash** [comment]
@Obicom  just update it yourself:
```
sudo pip3 install --upgrade alexapy
```

**Comment by Obicom** [comment]
@hmmkash  for Hass.OS user it will be not possible ....

**Comment by Obicom** [comment]
@hmmkash  I did the upgrade but the error in log is the same ....

![image](https://user-images.githubusercontent.com/25134482/54645454-5dc42500-4a9c-11e9-93e7-69d417446e7b.png)

**Comment by alandtse** [comment]
@Obicom That is a different known bug. Please see #127.

**Comment by Obicom** [comment]
Ok, done ... installed branch 1.2.3 and error is gone ... :)

**Comment by hmmkash** [comment]
@Obicom  just update it yourself:
```
sudo pip3 install --upgrade alexapy
```


> 
> 
> Ok, done ... installed branch 1.2.3 and error is gone ... :)

Nice!!
there is another update for alexapy if you upgrade your alexa_media custom component
