### ISSUE TITLE
Appdeamon

### ISSUE THREAD

**Issue by iVexilar** [keatontaylor/alexa_media_player#141]
How would one go about requesting a notification call in appdeamon using this.  I've tried just about everything I can think of however I ways get the NoneType error.

**Comment by alandtse** [comment]
This GitHub is probably not the best way to get an answer as there is a smaller technical audience reviewing these issues. Ask on the [forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/) which is more likely to find someone using appdaemon or find an appdaemon forum.
