### ISSUE TITLE
Custom Updater - Component URLs wrong

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa_media_player#143]
When looking at the WIKI entry to add the addin to custom updater you can see the line: https://raw.githubusercontent.com/keatontaylor/alexa_media_player/next/custom_components.json

Problem is, the next branch is not existent anymore. Maybe you might change this to dev branch, but in that case the json is still linking to the master branch and needs fixing.

**Comment by alandtse** [comment]
Thanks for pointing that out. It's fixed now in the wiki. 
I just realized it may be a pain to generate the right json file in the next branch so we may just deprecate the custom_updater instructions for next entirely if we can't find a easy way to keep it synced.

**Comment by niemyjski** [comment]
I have the files in my custom components directory and added the url to my config... I cannot get it to install and be listed on the custom_components widget.. Anyone else seeing this?

**Comment by alandtse** [comment]
@niemyjski It's not a `card_urls` it's a [`component_urls`](https://github.com/keatontaylor/alexa_media_player/wiki#custom_updater-versions--110)

**Comment by niemyjski** [comment]
Doh
