### ISSUE TITLE
Can do stream a mp3 file to alexa

### ISSUE THREAD

**Issue by keitetran** [keatontaylor/alexa_media_player#149]
Hi dev, this is very cool PJ
I from Vietnam, we need vietnames on alexa. Can you update this component for stream a mp3 file :( i need google TTS work with alexa . Please!!!

https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#directives

**Comment by alandtse** [comment]
No. Not possible as we do not provide any endpoint. It's an Amazon limitation as we only access the existing API.
