### ISSUE TITLE
Feature request: Alexa Skill Cameras streams 

### ISSUE THREAD

**Issue by freekeys** [keatontaylor/alexa_media_player#152]
It would be amazing if we could pull the camera streams from Alexa Skills which feed the FireTV/Echo Show (eg Blink camera skill) into the Home Assistant camera stream component! Is this possible? Thanks! :)

**Comment by alandtse** [comment]
Please note this is a custom_component and not the built in Alexa component.  That said, we are limited to what the Alexa app can actually do. If you can pull a camera stream in the Alexa app, please let us know, but until then I don't think we can.
