### ISSUE TITLE
[Question] What does it mean "Change notify component to autoload " in 1.2.4?

### ISSUE THREAD

**Issue by Obicom** [keatontaylor/alexa_media_player#154]
What does it mean? "Change notify component to autoload - You may have to remove existing notify configuration to avoid _2 service" Shall I delete the entry in configuration.yaml for notify.alexa_media?

**Comment by alandtse** [comment]
Yes you can. It should automatically create it now. I didn't test what happens if you left it in so wasn't sure if it's caused duplicate services.

**Comment by alandtse** [comment]
Correct, if you use the new notify targets you do not have to specify target.

**Comment by AngelofromTurin** [comment]
hi, 
where it write the new notify service? i dont see nothing in my configuration yaml....

**Comment by somar05** [comment]
> hi,
> where it write the new notify service? i dont see nothing in my configuration yaml....

It's a service, so you can use it into your configuration.yalm. Check your services in HA Developer tools - Services.
