### ISSUE TITLE
custom_updater

### ISSUE THREAD

**Issue by tomhoover** [keatontaylor/alexa_media_player#159]
I just added the `custom_updater` component, and added the following to my `configuration.yaml` file:
```
custom_updater:
  component_urls:
  # Released build
  - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
```

After restarting HA, I see the following on the custom `tracker-card` (recommended by `custom_updater`) after pressing the `UPDATE ALL` button:

![Screen Shot 2019-04-13 at 1 26 38 PM](https://user-images.githubusercontent.com/159040/56083844-e447fa00-5def-11e9-80f0-e2c026ef9dc0.png)

It appears to indicate that I'm tracking both `master` and `dev` branches (which I'm not)--I'm only tracking the `master` branch. It also indicates that I've updated the `dev` branch, but not the `master` branch. I'm *assuming* both are shown, as both `master` and `dev` are included in the [custom_components.json](https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json) file. I'm also *assuming* the `dev` branch is shown as updated, as it's listed second in [custom_components.json](https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json).

Further testing revealed `custom_components.json` should be unique between the two branches. I've submitted two pull requests (#157 and #158) to correct the issues in both the `master` and `dev` branches.

After applying the fixes, the `tracker-card` now correctly displays the following:
![Screen Shot 2019-04-13 at 2 01 25 PM](https://user-images.githubusercontent.com/159040/56084158-abf6ea80-5df4-11e9-9f4f-1b2007d5e14c.png)

**Comment by tomhoover** [comment]
After thinking about it a bit more, it might be easier to maintain by splitting `custom_components.json` into two separately-named files (e.g. `master.custom_components.json` and `dev.custom_components.json`), rather than using two different versions of the same filename in two different branches. (Otherwise, merging `dev` into `master` would not be clean.)

If you'd rather go this way, let me know and I'll modify the PRs.

**Comment by alandtse** [comment]
Thanks. I think we're just going to remove dev from the updater. Too much hassle to remember to update different files as we update.

**Comment by tomhoover** [comment]
PR #157 should take care of it then. I'll close #158.

**Comment by alandtse** [comment]
Thanks for the PR.
