### ISSUE TITLE
Players become unavailable sometimes. Ha reboot fixes this temporary.

### ISSUE THREAD

**Issue by Dielee** [keatontaylor/alexa_media_player#160]
As described above, my players become unavailable some times. But in the Alexa app they are online and working.

Error in log:

> 2019-04-17 22:55:59 ERROR (Thread-24) [websocket] error from callback <bound method WebsocketEchoClient.on_open of <WebsocketEchoClient(Thread-24, started daemon 1743549552)>>: [Errno 32] Broken pipe
2019-04-17 22:55:59 ERROR (Thread-24) [alexapy.alexawebsocket] WebSocket Error [SSL: BAD_LENGTH] bad length (_ssl.c:1949)
2019-04-17 22:56:02 ERROR (Thread-26) [websocket] error from callback <bound method WebsocketEchoClient.on_open of <WebsocketEchoClient(Thread-26, started daemon 1725801584)>>: [Errno 32] Broken pipe
2019-04-17 22:56:02 ERROR (Thread-26) [alexapy.alexawebsocket] WebSocket Error [SSL: BAD_LENGTH] bad length (_ssl.c:1949)

**Comment by alandtse** [comment]
@keatontaylor Any thoughts if this is ours or something we can guard against?

**Comment by alandtse** [comment]
@Dielee also, there should be more logs from alexa_media showing it falling back to general polling. Are you capturing the alexa_media logs?
Also, at that point, media_players should still update after 1 minute if your'e using HA or your voice to control them.  Is that not happening?

The alexa_media logs would look like:
```
email: Websocket failed: [Error] falling back to polling
```

**Comment by Dielee** [comment]
No, advanced debugging is not enabled this time..
My log also shows this error:

**Comment by keatontaylor** [comment]
@alandtse I was afraid that amazon might close web socket connections on an interval, maybe as they migrate their cloud based systems, etc. I'm. not sure our reconnect process is working well, or that we have proper checking for websocket failures since we're using it solely for status updates. I.E - besides the socket being closed, how do we know when we are no longer receiving push messages? 

I'm not 100% sure how to solve this, other than perhaps implementing a reconnect on a standard interval for websocket messages.

**Comment by alandtse** [comment]
@keatontaylor I believe I set the reconnect to only try once. It's supposed to be logging disconnect events so we can figure out when the disconnect is something we can reconnect to. My biggest concern with an indiscriminate auto reconnect is it may slam the server.  Hopefully we'll get some more logs on the disconnect.

**Comment by Dielee** [comment]
I have enabled debugging during the night and got an Error at 03:39 o'clock.
But I have to say that the component is stable again for the last day.

> WebSocket Error [Errno 110] Connection timed out


Debug log:
[home-assistant.log](https://github.com/keatontaylor/alexa_media_player/files/3106444/home-assistant.log)

**Comment by alandtse** [comment]
@Dielee Thanks for the logs. You can delete them now. The only timeout for alexa_media successfully reconnected. The other websocket errors you are seeing are coming from HA.  I'll close this for now, but feel free to reopen this if you have the same errors.  When that happens, we will need the logs for when it stopped working.

**Comment by Dielee** [comment]
So, updated to newest version 1.2.8. 
Everything works as it should, but my log gave me errors:

`WebSocket Error [SSL: BAD_LENGTH] bad length (_ssl.c:1949)`

`error from callback <bound method WebsocketEchoClient.on_open of <WebsocketEchoClient(Thread-28, started daemon 1751721072)>>: [Errno 32] Broken pipe`

`WebSocket Error [Errno 104] Connection reset by peer`

Debug log: 
[alexa_media_log.txt](https://github.com/keatontaylor/alexa_media_player/files/3151119/alexa_media_log.txt)
