### ISSUE TITLE
Client exceeded max pending messages [2]: 512

### ISSUE THREAD

**Issue by Dielee** [keatontaylor/alexa_media_player#161]
As shown above, log says `Client exceeded max pending messages [2]: 512`
and HA not updating media players anymore.

**Comment by alandtse** [comment]
I don't see the log. Did you include it?

**Comment by Dielee** [comment]
Fixed this by myself. 
I had an automation which pauses every group and player when TV goes on, unless it's playing or not. 
Now I added a check if player is playing and stopping only playing players.

Issue seems gone.

**Comment by Dielee** [comment]
Problem persists... ideas ?

**Comment by alandtse** [comment]
Can you please provide the logs with the error? You may be running into an Amazon throttling issue. Do you have an Everywhere group you can send the pause to?

**Comment by alandtse** [comment]
I feel like this my be related to #147

**Comment by Dielee** [comment]
This issue seems not to be related to alexa_media component. 
It's an HA issue.  https://community.home-assistant.io/t/help-client-exceeded-max-pending-messages/32276
