### ISSUE TITLE
alexa_media, it clearly wrongly used HA core lib ?

### ISSUE THREAD

**Issue by vMeph** [keatontaylor/alexa_media_player#162]
@alandtse  was wondering about this post on discord about alexa component
https://discordapp.com/channels/330944238910963714/427516175237382144/568340903333462017

**Comment by alandtse** [comment]
It may be true but I don't think it has any practical impact besides the log error when trying to shutdown. Are you seeing something broken otherwise?

**Comment by alandtse** [comment]
The fix of course is to either turn the calling function async or make everything synchronous. However, the cited lines are for the configurator which only should be an issue if someone fails to fully log in before the configurator is terminated.  We could do a further scrub throughout but I'm not sure what impact any of this has.

**Comment by vMeph** [comment]
@alandtse  all works fine off course, just tough you might wanted to know :)

**Comment by alandtse** [comment]
@keatontaylor Also, would like your input since I believe you have a stronger understanding of async for python. This is related to the configurator function where I broke up your single async login function into multiple sync helper functions which happen to call hass_async_add_job.
