### ISSUE TITLE
SOLVED: First configuration stuck after captcha

### ISSUE THREAD

**Issue by flashbackpa** [keatontaylor/alexa_media_player#163]
Hi,
i'm trying to use this component, cause i prefer Alexa's voice to Google one ;)
But after writing the needed configuration in configuration.yaml, and restarted the system (hass.io on raspberry), i can't go after the captcha window...
I mean, i write the captcha the window closes, and i find an entity named "Alexa Media Player - Captcha - *MYEMAILADDRESS* (configurator)"
I don't really know how to proceed further...
Help me please !
Thank you.

**Comment by alandtse** [comment]
https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-advanced-debugging

**Comment by flashbackpa** [comment]
Thank you @alandtse , looking at files generated by debug option, I noticed a typo on the amazon password ! 👍
