### ISSUE TITLE
Missing services.yaml and manifest.json for 0.92.0 Betas/Final

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa_media_player#164]
After I went to 0.92.0B1 and B2 I am greeted with these nice warnings now.

WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the alexa_media integration

Not only your component, almost ALL custom components I use are listed with such warnings. Thus I thought, I open a few reports ^^

**Comment by alandtse** [comment]
Thanks. 0.92 will also require a manifest.json.
https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

This is in the queue.

**Comment by hmmkash** [comment]
Hi,
Create the file services.yaml (empty file), and create manifest,json with content:
```
{
  "domain": "alexa_media",
  "name": "alexa Media",
  "documentation": "https://github.com/keatontaylor",
  "dependencies": [],
  "codeowners": ["@keatontaylor"],
  "requirements": []
}
```
and Reload Ha, it should work again
