### ISSUE TITLE
Echo Buttons (and possibly other Alexa Gadgets) showing on Sources list

### ISSUE THREAD

**Issue by gadgetchnnel** [keatontaylor/alexa_media_player#166]
The Sources list appears to pick up all Bluetooth devices connected to the Alexa device, and not just speakers or devices (such as mobile phones) using the Echo as a Bluetooth speaker. 
Since Alexa Gadgets (such as the Echo Buttons and the Echo Wall Clock) connect over Bluetooth, these are also being included in the list. For me that means that I have several Echo Buttons showing in the list.

Is it possible to filter this list so it only has speakers are included?
If the type isn't returned it may be possible to do it by name. I know Echo Buttons all have names starting with EchoBtn. I don't know about the Echo Wall Clock as this hasn't yet launched in the UK.

**Comment by alandtse** [comment]
We are pulling information from this [link](https://alexa.amazon.com/api/bluetooth?cached=false).  Can you use your appropriate region and provide us info for what Echo Buttons look like? Please mask any sensitive info like serial #s.

**Comment by gadgetchnnel** [comment]
Here are three devices from the **pairedDeviceList** collection for my Echo Dot:

Paired phone:
```
{
"address": "**:**:**:**:**:**",
"connected": true,
"deviceClass": "OTHER",
"friendlyName": "HM20PRO",

"profiles": [
"A2DP-SOURCE",
"AVRCP"
]
}
```

Bluetooth speaker
```
{
"address": "**:**:**:**:**:**",
"connected": true,
"deviceClass": "OTHER",
"friendlyName": "Altius001",

"profiles": [
"AVRCP",
"A2DP-SINK"
]
}
```

Echo Button
```
{
"address": "**:**:**:**:**:**",
"connected": false,
"deviceClass": "GADGET",
"friendlyName": "EchoBtnA5B",

"profiles": [
"AVRCP"
]
}
```

It looks like Echo Buttons and other Alexa Gadgets can be identified by their devcie class being GADGET. The phone and speaker both have a class of OTHER.

**Comment by alandtse** [comment]
I think the solution is to actually check for A2DP-Source in Profiles.

**Comment by alandtse** [comment]
@gadgetchnnel can you please test #170?

**Comment by gadgetchnnel** [comment]
@alandtse I've tested that and it appears to work well, excluding the Echo Buttons and showing my phone which was paired with the Echo Dot.
