### ISSUE TITLE
alexa_media does not generate unique IDs when adding second account

### ISSUE THREAD

**Issue by genem2** [keatontaylor/alexa_media_player#180]
I see #[124 ](https://github.com/keatontaylor/alexa_media_player/issues/124)is closed, but today I'm seeing this error after adding a second account to my alexa_media:

All appears to be working fine with that other account's Echo, however, the log file is reporting errors on all Echos. 

When I remove the second account, I just get the one routine warning line in the log.
When the second account is added back  .... Please see attached.
(My __init__.py is: __version__ = '1.2.5')

Thank you...

**Comment by alandtse** [comment]
If you reverse the order of accounts do you get the same warnings?

**Comment by vladtepz** [comment]
I've been seeing the same error since Feb 23rd when multi account support was first added, as reported in my last reply here: https://github.com/keatontaylor/alexa_media_player/issues/86#issuecomment-467854097

Everything works, I think I just got used to it since I was just so happy that multi-accounts work at all.

**Comment by genem2** [comment]
> If you reverse the order of accounts do you get the same warnings?

Appears so. Attaching.
[swapped_home-assistant.txt](https://github.com/keatontaylor/alexa_media_player/files/3152299/swapped_home-assistant.txt)

**Comment by alandtse** [comment]
I think I have a solution that will suppress the error log.  From what I can tell it has no impact on functionality, but let me know if you guys see differently.

**Comment by genem2** [comment]
I am _not_ detecting any functionally issue; just the log entries.  Tnx
