### ISSUE TITLE
Pause while talking

### ISSUE THREAD

**Issue by cubilon** [keatontaylor/alexa_media_player#183]
Anyone knows how to let Alexa take a short pause while speaking using notify service?
I tried:
"Welcome home.    ----      Everything is ok."
"Welcome home.  ,,,,,,,,        Everything is ok."

Same behaviour: she talks with no pauses. Any idea?

**Comment by alandtse** [comment]
Try "......". 

If you figure it out, please update the wiki with the information.  This type of question may get a better answer from the [forum ](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/) though.  The github is primarily for technical issues so you'll have less people seeing the question.
