### ISSUE TITLE
Feature Request: Alexa Guard

### ISSUE THREAD

**Issue by photinus** [keatontaylor/alexa_media_player#186]
It would be nice to be able to toggle the Alexa Home/Away feature for Alexa Guard now that the feature is GA

**Comment by alandtse** [comment]
Do you know if it's available yet either through the Alexa app as a routine or the website? Or if some other library has enabled it?

**Comment by keatontaylor** [comment]
It is available to turn on and off via the Alexa app, I actually looked to see if the API could be extracted via decompiling the APK, but I couldn't find any API that sets the Guard Home/Away mode, but I might've extracted an older APK.

**Comment by tiagofreire-pt** [comment]
This feature is not yet available for routines, only within the "settings -> guard" app flow.

Would be an awesome feature integrated with HA.

**Comment by eracknaphobia** [comment]
Here's what I was able to dig up with a rudimentary traffic sniffing.

Request:
`PUT https://alexa.amazon.com/api/phoenix/state`

Body:
`{"controlRequests":[{"entityId":"redacted","entityType":"APPLIANCE","parameters":{"action":"controlSecurityPanel","armState":"ARMED_AWAY"}}]}`

The armState can be
`ARMED_AWAY or ARMED_STAY`

**Comment by alandtse** [comment]
@eracknaphobia Thanks. We'll try that.

**Comment by tiagofreire-pt** [comment]
@eracknaphobia, the entityId could you explain what that is or where can we get it to trigger the away mode with that?

**Comment by eracknaphobia** [comment]
@tiagofreire-pt if you go here:
`https://alexa.amazon.com/api/phoenix?includeRelationships=true`

Look for the block of json that contains `RedRock` the entity_id should be what you need.
```
"manufacturerName": "Amazon",
"friendlyDescription": "RedRock panel",
"modelName": "REDROCK_GUARD_PANEL",
"deviceType": "",
"version": "0",
"friendlyName": "redacted",
"friendlyNameModifiedAt": 1557866303006,
"capabilitiesModifiedAt": 1557866303006,
"ipAddress": "",
"port": "",
"entityId": "redacted",
 
```

**Comment by tiagofreire-pt** [comment]
@eracknaphobia, Thanks!

But with -u user:password I couldn't get the curl command to work, as it returns 401 error message.

**Comment by eracknaphobia** [comment]
I should mention that I did not post header values (cookies, etc.) in the request for readability. You'd need to automate the login process in order to get those values, before you'd be able to run it through curl. Better to let this component do that as it already handles this.

**Comment by tiagofreire-pt** [comment]
@eracknaphobia, OK, I have to wait on this. :)

BTW, I see a device named "Redrock panel" in this url: https://alexa.amazon.com/spa/index.html#appliances

It's possible to trigger it through this custom_component?

**Comment by eracknaphobia** [comment]
@tiagofreire-pt Interesting, I see that too.
No, not that I'm aware of.

**Comment by alandtse** [comment]
If you guys see a way to tell status, let me know. Otherwise we may just implement it as a service instead of a switch.

**Comment by photinus** [comment]
Any tips on how to get Fiddler to decrypt the traffic from the Alexa android app? I can capture some other apps, but not the alexa app, just get tons of connects and no data.

**Comment by eracknaphobia** [comment]
@alandtse Here the request that checks the status:

Request
`POST https://alexa.amazon.com/api/phoenix/state`
Body:
`{"stateRequests":[{"entityId":"AAA_OnGuardSmartHomeBridgeService_6252b2f5-6e92-326a-9b1e-098027992a01","entityType":"APPLIANCE"}]}`

Response:
`{"deviceStates":[{"entity":{"entityId":"AAA_OnGuardSmartHomeBridgeService_6252b2f5-6e92-326a-9b1e-098027992a01","entityType":""},"capabilityStates":["{\"namespace\":\"Alexa.SecurityPanelController\",\"name\":\"armState\",\"value\":\"ARMED_STAY\",\"timeOfSample\":\"2019-05-16T13:13:21.998Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}"],"error":null}],"errors":[]}`

**Comment by alandtse** [comment]
I have get_status working as a service call. Still working on the set_state. 

I am wondering if we can catch any guard events. I don't see anything on websockets yet.

**Comment by eracknaphobia** [comment]
@alandtse Yeah, I'm pretty sure it's the entityId of my phone / alexa app. I wonder if you could switch out the entityId of an echo device as they would be able to set the state as well.

**Comment by eracknaphobia** [comment]
Found the guard history url. Not sure if it'd be useful or not.

Request
`POST https://alexa.amazon.com/api/smarthome/v1/history/events`

Body
`{"timestamp":{"from":"2018-01-01T00:00:00.000Z","to":"2118-01-01T00:00:00.000Z","sortOrder":"DESC"},"filter":{"type":"V1","filterExpression":[{"redRockEvent":"RedRockHistoryEvent","history_event_type":"Alexa.Event.ChangeReport"},{"redRockEvent":"RedRockHistoryEvent","history_event_type":"Alexa.Event.HomeOccupancyState"}]},"maxResults":20}`

![image](https://user-images.githubusercontent.com/8268725/57969010-bfd7c400-793f-11e9-9fb1-e773cc07db02.png)

**Comment by alandtse** [comment]
@eracknaphobia Sorry I'm confused on the entityId your'e using for the `set`.  Earlier you mentioned it's the `entityId` under the `RedRock panel`.  But in your example for the `get` it looks like you're instead using the `applianceId`.  Your last statement also indicates a entityId of your phone. I'm not sure where you're finding that value for your phone either.  Most of the other functions use the Echo device serial numbers, but I don't think that works for entityId.

Thanks for the url. Can you provide the events for each of the events or let me know how you're testing them so I can generate them? While we could do a polling, the preference would be to figure out either websockets or how to get a similar push notification.

**Comment by alandtse** [comment]
I'm currently stuck on the entityId issue for setting the AlarmState.  Until I can get it working, then I don't think we'll fully develop the feature.  

For those who want to play with it, you'll need my guard branch for [alexa_media](https://github.com/alandtse/alexa_media_player/tree/guard) and for [alexapy](https://gitlab.com/alandtse/alexapy/tree/guard).

This branch will expose two services:
`alexa_media.get_guard_state`
Use the applianceId for your RedRock entity.
```json
{ "entity": "AAA_OnGuardSmartHomeBridgeService_XXXXX"}
```
This will output the debug logger for `alexapy.alexaapi`
```irc
2019-05-19 18:39:05 DEBUG (Thread-11) [custom_components.alexa_media] Service get_guard_state for AAA_OnGuardSmartHomeBridgeService_XXXXX : []
2019-05-19 18:39:05 DEBUG (Thread-11) [alexapy.alexaapi] Response: {'deviceStates': [{'entity': {'entityType': '', 'entityId': 'AAA_OnGuardSmartHomeBridgeService_XXXXX'}, 'error': None, 'capabilityStates': ['{"namespace":"Alexa.SecurityPanelController","name":"armState","value":"ARMED_STAY","timeOfSample":"2019-05-20T01:39:05.442Z","uncertaintyInMilliseconds":0,"deepQuery":true,"timeOfStateChange":""}']}], 'errors': []}
```
`alexa_media.set_guard_state`
This is the entity that I can't figure out.
```json
{ "entity": "HELP?", "state":"ARMED_AWAY"}
```
This is the faulty error log which indicates a HTTP 400 error for now.
```
2019-05-19 18:44:19 DEBUG (Thread-2) [custom_components.alexa_media] Service set_guard_state to ARMED_AWAY for HELP? : []
2019-05-19 18:44:19 DEBUG (Thread-2) [alexapy.alexaapi] Response: <Response [400]> for data: {"controlRequests": [{"entityType": "APPLIANCE", "entityId": "HELP?", "parameters": {"armState": "ARMED_AWAY", "action": "controlSecurityPanel"}}]}
2019-05-19 18:44:19 ERROR (Thread-2) [alexapy.alexaapi] An error occured accessing AlexaAPI: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```

**Comment by eracknaphobia** [comment]
@alandtse I PM'ed you my fiddler traffic capture through the home assistant forums. Figured it'd be easier if you could see what I'm seeing.

As for the events, I was just pulling up broken glass and smoke alarm on youtube and playing them near my echo's after putting them in away mode.

**Comment by alandtse** [comment]
@eracknaphobia Thanks! You can delete the file now.

Ok, I got it working. I had a dumb error in that I was doing a post instead of a put. I'll investigate if we should do an alarm control panel or just leave it as a service.

**Comment by eracknaphobia** [comment]
Awesome! Thanks for implementing this so quickly.

**Comment by keatontaylor** [comment]
My suggestion would be to make it at least a switch entity if not going all the way to an alarm panel.

**Comment by JLFN** [comment]
@alandtse is it possible to make a binary_sensor for sound ?

**Comment by alandtse** [comment]
@JLFN No. There isn't any mechanism to report that Alexa received a sound.  The event log shows instances when the wake word was found only.

**Comment by alandtse** [comment]
Ok, have a working alarm_control_panel in my guard branch; will need the relevant alexapy branch too. I'll plan this for the 1.3.0 branch.

**Comment by tiagofreire-pt** [comment]
@alandtse , could you share that code, please?

**Comment by alandtse** [comment]
@tiagofreire-pt I posted the [link](https://github.com/keatontaylor/alexa_media_player/issues/186#issuecomment-493813912) above.

**Comment by tiagofreire-pt** [comment]
@alandtse, is it possible to add a sensor for the trigger event of Alexa sensing something wrong and also with the attribute of the type detected (glass, fire alarm, etc)?

I think this would be useful to trigger automations, recording states and events.

**Comment by alandtse** [comment]
I haven't found any good way to detect events. I'm not seeing any websocket traffic and polling the event log is something we're trying to cut back on. Unless we can find some reliable event to track through the API, I won't be able to add any event sensors unfortunately.

**Comment by bbrendon** [comment]
Also, if you guys ever figure out a way to _not_ get alerts on your phone about it being activated or deactivated (coming/going), please post.

When people are coming and going I'm constantly getting alerts. _super duper_ annoying.

**Comment by alandtse** [comment]
Under guard mode settings you can disable the app notifications. [Reddit](https://www.reddit.com/r/amazonecho/comments/bsqlh1/disable_guard_notification/)

**Comment by walthowd** [comment]
Just FYI guys, started using the API calls to arm/disarm the guard mode and after one day, the white/blue spinning guard mode light is stuck on my five dots. Even if I turn off Alexa Guard via voice, and reboot the Echo dots the light stays on. I've disabled Guard completely, rebooted the Dots, forgot all devices from alexa.amazon.com, etc, etc -- hard rebooted dots -- all in various iterations. Still spinning blue/white light.
