### ISSUE TITLE
Captcha image not loading

### ISSUE THREAD

**Issue by alextircovnicu** [keatontaylor/alexa_media_player#196]
Hi!

History of this issue:
I installed at the beginning of the year alexa_media_player and successfully configured it and use it for couple of months.  One day I got a notification that I need to configure it but the Captcha image was not loading. Back then I managed to solve this  by upgrading the component. 
I have now the same issue (and I am using the latest version):
![image](https://user-images.githubusercontent.com/24647444/58365712-8fa49e00-7ec8-11e9-9218-2d64dc5539d3.png)

I am using:
Home Assistant 0.92.1 - hassbian
Amazon: Germany 

Thank you!

**Comment by alandtse** [comment]
Click the confirm button and it will ask for a new image.

**Comment by bachoo786** [comment]
I have installed this via HACS restarted HA but do not get the "Captcha" in my HA notifications. I can see my alexa as a media player in HA but when I do a TTS, alexa replies saying i need to configure in Alexa?

Any help please?

**Comment by alandtse** [comment]
You're set up without a captcha. See the FAQ re TTS in the UI

**Comment by PrathikGopal** [comment]
I had this issue, for anyone else looking for resolution.

1. I deleted the integration from HACS and cleared the pickle files 
2. Re-added the Alexa Media player from HACS store. 
3. Restarted HA like twice and then i got the captcha visible.

Hope it helps.
