### ISSUE TITLE
Add support for HACS

### ISSUE THREAD

**Issue by ipodmusicman** [keatontaylor/alexa_media_player#201]
Hi there

Are you going to add support to allow updating of this component using HACS instead of custom_updater as custom_updater is EOL?

**Comment by alandtse** [comment]
A link to HACS would be nice.

**Comment by rbhr** [comment]
> A link to HACS would be nice.

https://github.com/custom-components/hacs/releases/tag/0.1.0

Google took me to a Twitter on it. Was news to me too!

**Comment by vMeph** [comment]
this would be nice to make it happen. HACS rox....

**Comment by xatr0z** [comment]
It works after placing the integration in another directory.

After the pull requests is merged you can use it by adding `https://github.com/keatontaylor/alexa_media_player` in HACS --> Settings. (In the meantime, you can use `https://github.com/xatr0z/alexa_media_player`)/

**Comment by strangedesign13** [comment]
So I have tried to add both ```https://github.com/keatontaylor/alexa_media_player```  and ```https://github.com/xatr0z/alexa_media_player```in HACS --> Settings. Both of them error out with "custom_components does not exist in the repository."

What am I missing?

**Comment by alandtse** [comment]
1.3.0 is not released yet. It will be released this weekend.

**Comment by strangedesign13** [comment]
Ahhhh, thanks. Appreciate it.
