### ISSUE TITLE
Alexa Component crashed

### ISSUE THREAD

**Issue by Pirol62** [keatontaylor/alexa_media_player#206]
Got thos error:

An error occured accessing AlexaAPI: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 8 column 1 (char 7)',)

Version 0.93.2

**Comment by Pirol62** [comment]
After a restart and captcha authentification, everything worked again.
But why did the api crashed?

**Comment by alandtse** [comment]
The error you saw means it was no longer able to access data. By restarting and redoing the Captcha you fixed the login issues.
