### ISSUE TITLE
Captcha Loop

### ISSUE THREAD

**Issue by JoeStratton** [keatontaylor/alexa_media_player#214]
After entering the captcha it just reloads and asks for another captcha, when I debug it its showing that Amazon is asking for the captcha along with my credentials again but the UI doesnt show that so it fails.

Under the captcha it reads: "Important Message! To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below. "

**Comment by BeBsCh** [comment]
Hi!
I have the same problem.
Delete the Alexa Entitiy at the configuration.yaml , reboot Hassio and add the Alexa Entity at the configuration yaml without "!secret". Reboot Hassio. It works. Now you can change back to !secret.

**Comment by alandtse** [comment]
When you say the "UI doesn't show that",  please confirm you're using the notification button in the top right of HA to access the configuration UI.  That will load the UI for entering the captcha and 2FA.

Assuming you're answering the captcha correctly, the next step is to get the [advanced debugging logs](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-advanced-debugging) which would show the login page you're failing at.

**Comment by JoeStratton** [comment]
Sorry I must not have been clear, but yes when I say i debug it i meant i enabled debugging. It is showing the html page as a captcha PLUS account credentials while the UI is only showing the captcha, hence the failure.

**Comment by JoeStratton** [comment]
@BeBsCh this workaround did fix the issue, thanks!

**Comment by alandtse** [comment]
Thanks. The reason it doesn't show the credentials is it is using the configuration. By enabling debugging you can see what we're passing back to Amazon. Glad to hear the workaround helped.

**Comment by JoeStratton** [comment]
sadly it only worked until the next restart

**Comment by alandtse** [comment]
Please provide debug logs.

**Comment by alandtse** [comment]
Please reopen when you're ready to continue.

**Comment by sfgabe** [comment]
I'm also caught in the captcha loop. Workaround above and turning off 2 factor auth didn't fix it. I noticed when I log in normally, after the captcha I have to respond to a text message so maybe that's the issue.
