### ISSUE TITLE
Unable to turn on guard mode

### ISSUE THREAD

**Issue by monsieurlatte** [keatontaylor/alexa_media_player#222]
First off, this amazing!  I have done so much with it right away.  I was looking at adding a trigger to enable Guard Mode however under alarm_control_panel.alarm_arm_home is alarm_control_panel.home_alarm, i dont see another entity tied to amazon to trigger that?  Or am I missing something?  I have v 1.3.0 installed.  I have guard mode enabled in my alexa app and it's working fun.

**Comment by alandtse** [comment]
As I just release 1.3.0 about 10 minutes ago, I'm not sure if you actually had it installed.  Please verify you're on 1.3.0 and if you're still seeing issue provide some [logs](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) from `alexapy`

I'll close this for now, but please reopen if it persists.

**Comment by monsieurlatte** [comment]
Gosh I feel like a heel, thanks, you're right, I didnt realize I didnt have 1.3.0, I just updated and it's there now as an entity.

**Comment by alandtse** [comment]
No biggie, I teased it on the forum when I had it staged and you're not the only one who thought I meant I had released it.
