### ISSUE TITLE
HACS - custom repository failed

### ISSUE THREAD

**Issue by TomboCZ** [keatontaylor/alexa_media_player#225]
Can't add keatontaylor/alexa_media_player (1.3.0) to HACS respository

1. URL "**https://github.com/keatontaylor/alexa_media_player/**"
failed with error message "_keatontaylor/alexa_media_player/ is not a valid format correct format is 'https://github.com/DEVELOPER/REPOSITORY' or 'DEVELOPER/REPOSITORY'._"
2. URL "**https://github.com/keatontaylor/alexa_media_player**"
failed with error message "_Could not add https://github.com/keatontaylor/alexa_media_player at this time, check the log for more details._"
---log---
`2019-06-23 12:05:52 [custom_components.hacs.hacs] keatontaylor/alexa_media_player - No acceptable js files found
2019-06-23 12:05:53 [custom_components.hacs.hacs] keatontaylor/alexa_media_player - Could not register.`
---log---

**Comment by vMeph** [comment]
all working perfect here...
![1](https://user-images.githubusercontent.com/12812111/59974940-073e1980-95aa-11e9-85e8-8557fa0aa67a.png)

**Comment by vMeph** [comment]
when adding the link did you select Type: integration?

**Comment by ludeeus** [comment]
The issue is the `/` at the end of "https://github.com/keatontaylor/alexa_media_player/"
Use `https://github.com/keatontaylor/alexa_media_player` or `keatontaylor/alexa_media_player` and it will be valid.

**Comment by TomboCZ** [comment]
The problem was in the "integration". Solved. Thanks for your help and I'm going to close this issue.
