### ISSUE TITLE
Method "show" doesn`t work for announcements

### ISSUE THREAD

**Issue by goermezer** [keatontaylor/alexa_media_player#231]
I would like my Echo Show to beep and show a message:

{
"message":"test",
"title":"My title for Echo show",
"data":{"type":"announce", "method":"show"},
"target":["5435435435434534GSGSFD"]
}

But "method":"show" seems not to work. Echo Show does not beep or show the message, when sending above call using home assistant service interface.

**To Reproduce**
1. Copy the JSON string above and replace the serial of "target" with the serial of your Echo Show
2. Go to 'Services'
3. Select service "notify.alexa_media"
4. Paste the JSON string into the service data field
5. Click "Call Service"
6.. Nothing happens, no error in log

**Expected behavior**
Echo Show with serial 5435435435434534GSGSFD beeps and shows the title and message of above code.

**System details**
 - Home-assistant 0.95.0: 
 - Hassio: No
 - alexa_media  version 1.3.0
 - alexapy version 0.7.0

I`m running home assistant in a docker container.

**Comment by alandtse** [comment]
Can you confirm Announce works with the 'speak' method and that the 'all' method also allows the audio to work?  Also, if you use the Alexa App to create a routine to replicate this announcement, does that also work for `show`?

**Comment by goermezer** [comment]
Yes, I can confirm, that 'speak' and 'all' works as expected.

**Comment by alandtse** [comment]
When you say works as expected, does `all` show the message on the Echo Show?

What about if you make a routine in the Alexa App to Announce? Does it also show the text?

**Comment by goermezer** [comment]
Echo shows following behavior:
"tts" -> Speaks and shows the message - not exactly what is expected, but we can live with it
"show" -> does nothing
"all" -> speaks and shows the message

An announcement from a routine in Alexa app, speaks and shows the message.

**Comment by alandtse** [comment]
Weird. The Alexa app doesn't appear to show the option anymore to just send a `show`. I'll ask the forums but Amazon may have removed that functionality.

**Comment by goermezer** [comment]
Ok. It would be cool, if this works. It's very annoying when you listen to music and Alexa suddenly says, that someone opened and then closed the garage door. A short beep and showing a message is more than enough.

**Comment by alandtse** [comment]
I'll leave this issue open for probably another week to see if anyone has the same issue. After that I'll close this and update the documentation removing the "show" option since it looks like it's gone now.

**Comment by goermezer** [comment]
I found that Amazon provide SSML to reduce the voice. As a workaround I tried it with the service tool first. But only the opening SSML tag is shown on the Echo Show with this message:

{ "message": "<prosody volume='silent'>Hallo</prosody>", "data": { "type":"announce", "method":"speak" } }

**Comment by alandtse** [comment]
Updated the wiki and crossreferenced to here. Closing for now.  Thanks again for reporting.
