### ISSUE TITLE
Text To Speak window not functional?

### ISSUE THREAD

**Issue by monsieurlatte** [keatontaylor/alexa_media_player#232]
**Describe the bug**
When you click on the three dots and you get the box at the bottom for Text To Speak, I can't get it to work no matter what I do?
**To Reproduce**
Click 3 dots, type text into Text to speak, click mail/arrow icon.

**Expected behavior**
I would assume alexa would speak those words :) 

**Screenshots**

**System details**
 - Home-assistant (version): 0.95.0
 - Hassio (Yes/No): yes but everything else works fine.  
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Additional context**

**Comment by alandtse** [comment]
This a known [incompatibility with the built in UI card](https://github.com/keatontaylor/alexa_media_player/wiki/FAQ#sorry-text-to-speech-cannot-be-read-with-the-alexa-tts-media-player-service).  We don't do TTS the same way as other Media Players so the built in GUI won't recognize it. Please us the Notify function as explained in the Wiki.
