### ISSUE TITLE
Group of echo device created through Alexa App are not shown in Home Assistant

### ISSUE THREAD

**Issue by pilip87** [keatontaylor/alexa_media_player#240]
**Describe the bug**
Group of echo device created through Alexa App are not shown in Home Assistant

**To Reproduce**
1. Add a Group to Alexa App
2. Add some Echo to this group
3. Restart Home Assistant

**Expected behavior**
Find group of device

**System details**
 - Home-assistant (version): 0.95.4
 - Hassio (Yes/No): NO
 - alexa_media  (version from `const.py` or HA startup): 1.3.1
 - alexapy (version from `pip show alexapy` or HA startup): Version: 0.7.0

Can someone help me? Thank you!

**Comment by pilip87** [comment]
Solved! I created group as "group" and not as "speaker for multiroom music"

**Comment by genem2** [comment]
> I created group as "group" and not as "speaker for multiroom music"

Encouraged by this I deleted my multiroom music (which appeared in HA as media_player.everywhere), and created a standard group. However, I'm not allowed to select any of the Echos that are already part of a room (part of another group).  I guess you must not have this.

Also: media_player.everywhere has no value to this media_player component, as per what you point out in the wiki: **Play in Alexa groups**.

I'm really not following this text:

> It is currently not possible to play to an Alexa group using routines. However, there is currently a hack that may or may not work where you can play to an Alexa group using any Alexa entity on that account. For example, to play to the "everywhere group". _NOTE: We are sending to media_player.guest_room instead of media_player.everywhere_

I'm not clear on what that's suggesting.
Appreciate any guidance.
Tnx.

**Comment by mkuhnke71** [comment]
Still cant use media_player.everywhere for playing music

Any thoughts?
creating an HA group works for saying text but its not in sync.

Using this for playing music does nothing at all
