### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by lweberru** [keatontaylor/alexa_media_player#242]
**Describe the bug**
The TTS component of the component dont work for me. I tried it in different ways. One is within the mini-media-player the other one is a direct call of the service "alexa_media". I tried both with or without the entity_id/target variants. The echo just dont "speak" to me. I dont get any error entry in the log or in the frontend. What is still working is by using a script called alexa_remote_control.sh of alex(at)loetzimmer.de
The rest of the alexa_media component is working fine. I am using HACS to always have newest version of this component. So it is v1.3.1 right now.

Next thing could be to enable a specific debug, right?

Regards

**Comment by alandtse** [comment]
Are you using the [notify](https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component) component? `media_player.tts` is deprecated and not supported.

**Comment by lweberru** [comment]
Yes I am using media_player.alexa_media service as you described it in your wiki. For example "notify.alexa_media_echo_wohnzimmer" or "notify.alexa_media"

**Comment by alandtse** [comment]
Please show the exact commands you are using. After that, we'll need debug logs for alexapy.

**Comment by lweberru** [comment]
service: 
notify.alexa_media_echo_wohnzimmer
data:
{
"message":"Hallo",
"data":{"type":"tts"}
}

or

service: 
notify.alexa_media
data:
{
"message":"Hallo",
"data":{"type":"tts"},
"target":["media_player.echo_wohnzimmer_2"]
}

**Comment by lweberru** [comment]
Site note (I think not relevant within this issue): The log has an error during setup of component:

```
2019-07-04 10:28:24 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 35, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 88, in __init__
    guard_dict = (data['locationDetails']
TypeError: 'NoneType' object is not subscriptable

```

That is because, alexa guard is not yet available in germany.

**Comment by lweberru** [comment]
I enabled debugging and als added :

```
notify:
  - platform: alexa_media
    name: alexa_media

```
to the config.

Now it is working (also via the mini media player). I am confused now. I thought this config entry is optional?

Regards

**Comment by alandtse** [comment]
Thanks for the Alexa Guard note. I'll see about fixing that too.

The notify should be completely optional. The restart probably made it login correctly.  We create multiple connections whenever we do different things with Amazon. Updates on the media player are one persistent connection, commands to the services (e.g., notify) are a separate connection. It's possible that the separate connections may not login properly without a restart.

I'll close this for now, let me know if you see the problem recur.
