### ISSUE TITLE
No tts.notify

### ISSUE THREAD

**Issue by gbdavidx** [keatontaylor/alexa_media_player#247]
**Describe the bug**

**To Reproduce**
1. i installed the latest version from HACS

**Expected behavior**
having a tts notify for alexa

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Additional context**

**Comment by alandtse** [comment]
I don't understand the issue. Is there no `notify.alexa_media` service?

**Comment by alandtse** [comment]
Please reopen when you're ready to discuss.
