### ISSUE TITLE
Automation syntax when using GUI editor

### ISSUE THREAD

**Issue by mattnewham** [keatontaylor/alexa_media_player#250]
**Describe the bug**
I dont know how to format the automation action when using the GUI editor. I just get an error saying extra keys not allowed at 'data' 'type'

**To Reproduce**
1. Go to automation editor
2. Type this in:

Call Service

notify.alexa_media

`{
  "data": {
    "type": "announce"
  },
  "message": "Yo Remco.. The washing machine is finished. Get off the couch.",
  "target": [
    "media_player.bedroom_echo",
    "media_player.office_echo"
  ]
}`
3. Run automation
4. See error ` Error while executing automation automation.test_alexa. Invalid data for call_service at pos 1: extra keys not allowed @ data['type']`

**Expected behavior**
No error.

**Screenshots**

**System details**
 - Home-assistant (version): Latest stable
 - Hassio Yes
 - Fresh install of alexa_media_player from HACS

**Comment by mattnewham** [comment]
Syntax works in scripts, not in automations

**Comment by alandtse** [comment]
Please consult HA documentation on how to properly format HA automations.  I believe the wiki may have some [examples of automations](https://github.com/keatontaylor/alexa_media_player/wiki/Automation-examples) you can use.

**Comment by mattnewham** [comment]
I’ve consulted the documentation, as you can see from my example it is
taken from the wiki. The issue is the formatting required by your component
is not supported in the new automations.yaml when used with the gui editor.
Two “data:” fields are not allowed.

As I mentioned, the same formatting works in scripts but not in automations.
