### ISSUE TITLE
Can't reset pickle / cookie file

### ISSUE THREAD

**Issue by iainsimons** [keatontaylor/alexa_media_player#255]
**Describe the bug**
Apologies, this might not be an Alexa_media_player bug, but a hassio one. 

I'm trying to force the reset of the cookie, by deleting the pickle file (as advised in the FAQ), as authentication is failing. 

I've tried deleting it using FTP and the configurator, also tried deleting the entire folder and re-uploading it, but I can't refresh the cookie file. It keeps getting replaced by a pickle file with the contents :"'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte"

Could anyone advise how to force the captcha process again?

**Comment by jlvandusen** [comment]
I am also receiving this after upgrading to v2.0
deleted it and rebooted.... keeps going through loop trying to authenticate (never prompts) and then captcha.
