### ISSUE TITLE
Error while setting up platform alexa_media - KeyError: 'csrf'

### ISSUE THREAD

**Issue by eifinger** [keatontaylor/alexa_media_player#258]
**Describe the bug**
TTS was not working anymore. I suspected an old cookie etc, deleted the .pickle file and restarted homeassistant which always worked. Configuration with 2FA seemed to work. Afterwards I started to see the following errors in the log:
```bash
Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 35, in setup_platform
    hass)  \
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 73, in __init__
    self.alexa_api = AlexaAPI(self, login)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 51, in __init__
    csrf = self._session.cookies.get_dict()['csrf']
KeyError: 'csrf'
````

**To Reproduce**
1. Delete .pickle
2. Restart HA
3. Configure (Login)
4. Error appear

**Expected behavior**
Media Players should appear along the functionality

**Screenshots**

**System details**
 - Home-assistant (version): 0.95.4 (docker)
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v1.3.1
 - alexapy (version from `pip show alexapy` or HA startup): 0.7.0

**Additional context**

**Comment by alandtse** [comment]
Thanks for reporting. I suspect Amazon changed something with the login. Will have to look into it. Unfortunately I'm traveling for a couple weeks so can't do much till I'm back.
You have total loss of functionality right?

**Comment by eifinger** [comment]
Unfortunately yes, total loss.

**Comment by tlpbu** [comment]
Have the same issue on hassio as well with latest HA.

**Comment by anrada73** [comment]
same problem.

**Comment by jmutnick** [comment]
same problem here

**Comment by jfautley** [comment]
It looks like Amazon have tweaked the API, and the AlexaPy library no longer gets the CSRF token from the login URL (and there's no error checking in the __init__ function there).

Given the upstream maintainers lack of time, I've forked the AlexaPy repo and updated the site - I'd raise a PR but it's a one line change and I've not done anything to actually test it - but it works for me.

You can find the updated repo at https://gitlab.com/jfautley/alexapy - I've tested this against an Amazon UK account using Hass.IO.

To install (on Hass.IO), SSH into your instance and run:
`pip3 install --target /config --no-dependencies git+https://gitlab.com/jfautley/alexapy`

For other Home-Assistant installs, you should be able to use `--target /path/to/config/deps` but for some reason the PYTHONPATH on Hass.IO is messed up... 🤷‍♂

**Comment by alandtse** [comment]
Thanks @jfautley . I'm currently traveling abroad but should be able to make the fix when I'm back. @keatontaylor any chance you can test/implement before then?

**Comment by jmutnick** [comment]
@alandtse, I downloaded the new file and it worked for me!  Thanks @jfautley

**Comment by genem2** [comment]
@jfautley , _Thank you!_  
Alexa can get back to keeping my kids on task!

**Comment by erichter2018** [comment]
Not fully understanding how to install this...  Should I completely uninstall the original plugin and install this instead?  or just install it over it?

**Comment by Xaos1990** [comment]
How do i install this on HassOS? 
When SSHing i cant pip3 or pip anything really (python isnt running there). I think i dont really understand the dockers setup in hassos/hassio (still very new to hass).

**Comment by jkpe** [comment]
@jfautley thank you
I replaced the following directory with the files [here](https://gitlab.com/jfautley/alexapy/tree/master/alexapy) and restarted but am still getting the same error mentioned in the first post, what am I doing wrong?

```
homeassistant@homeassistant:~$ locate alexalogin.py
/srv/homeassistant/lib/python3.6/site-packages/alexapy/alexalogin.py
```

**Comment by Ryanmt-Deep3** [comment]
Ensure you delete the .pickle file out of your config folder.

Just tested - fix works fine for me too. Thanks @jfautley

**Comment by jkpe** [comment]
> Ensure you delete the .pickle file out of your config folder.
> 
> Just tested - fix works fine for me too. Thanks @jfautley

Ah yes, working now, thank you

**Comment by Xaos1990** [comment]
Its working again, thanks @jfautley

**Comment by erichter2018** [comment]
I'm sorry for being a noob but could someone just give me quick pointers about how to install this?  I installed the original media player via HACS on Hassio, but I'm not sure how to upgrade/replace alexapy.

**Comment by fogarty** [comment]
First a huge thx @jfautley now works again!

@erichter2018 the simplest way would be to go to the "Configurator" then clic on settings and on "Execute shell Command"
Paste here the command given by Jon:
`pip3 install --target /config --no-dependencies git+https://gitlab.com/jfautley/alexapy`

Then don't forget to delete your .pickle file in your /config directory and reboot ;-)

**Comment by petestanley112** [comment]
so I'm one step closer now. although nothing seems to work. all Alexa's show is in standby and won't change state no matter what I do. 

any ideas?

**Comment by yinkastihl** [comment]
@jfautley I read through the thread but I am confused as to where to add the alexapy folder. Would it be under custom_components or it would be under python3.7/site-packages.
I have followed all other step and still didn't have my alexa showing or seeing media_player.alexa.tts

see my error below

Error while setting up platform alexa_media

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 66, in setup_platform
    hass)
  File "/config/custom_components/alexa_media/media_player.py", line 96, in __init__
    self.alexa_api = AlexaAPI(self, login)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 51, in __init__
    csrf = self._session.cookies.get_dict()['csrf']
KeyError: 'csrf'

**Comment by yinkastihl** [comment]
Finally I was able to have it work. Thanks

**Comment by petestanley112** [comment]
Did you get it working or just have a lack of errors in the logs... still trying to resolve that all my devices are only showing as standby. Cant get home assistant to talk to alexa seems as it can find them but cant do anything more.. they all show up as entities but cant as I say do anything else.

**Comment by yinkastihl** [comment]
Sorry, all my alexa devices are just showing up but coudn't use is as tts. I could not send a message in home assistant to my alexa dot. Also I do not see media_player.alexa_tts show in services. I previously use my echo dot as door chime but not after this upgrade
Does any one have a resolution to this.

**Comment by petestanley112** [comment]
Exactly my issue.

**Comment by yinkastihl** [comment]
Finally able to get it. with the new update, media_player.alexa_tts is no longer been used but rather notify.alexa_media
see my automation below (i send notification to my phone, have echo dot announce and have fire tablet do tts). You have echo dot tts but fire table can ONLY do TTS and not Announce

  alias: Send notification when front door open
  trigger:
  - entity_id: binary_sensor.front_door
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Front Door Open
    service: notify.iosapp_xyz_iphone
  - data:
      data:
        type: tts
      message: Front door open.
      target:
      - media_player.xyz_fire
    service: notify.alexa_media
  - data:
      data:
        type: announce
      message: Front door open
      target:
      - media_player.xyz_echo_dot

**Comment by petestanley112** [comment]
Will have a play tomorrow. Is this working now then. How have you over come the standby issues or did you not have that problem. Oh thank you for posting your automations you have saved me some time figgering it out when I get the tts working..

**Comment by yinkastihl** [comment]
@petestanley112 Alexa device are always in standby mode until you play something on the device, then you can pause, increase/decrease volume.

**Comment by mrnix1001** [comment]
@jfautley This fixed it for me as well! Thank you!

**Comment by petestanley112** [comment]
Mine stay in standby regardless. 

Quick note to moderators if this branch of chat is off topic can you point me I to the direction where I can resolve my problems I have now. Thanks

**Comment by 3ative** [comment]
Thanks for the fix guys. @jfautley & @fogarty 
My TTS stopped this morning - Both HA Automation and Node-Red working again after installing new code.

**Comment by petestanley112** [comment]
I have it working now also, well tts anyhow. Still how as in standby not that I care it's not a service I intend to use.

**Comment by mattnewham** [comment]
Not sure how you guys are installing the fix? I'm running hass.io in a VM, but I dont have pip or anything available in the core-ssh shell? I also dont have a .pickle file in my config directory either? my echo devices are showing up, but TTS doesnt work

**Comment by 3ative** [comment]
@mattnewham Mine's installed on a VM too (unRaid server). Just follow fogarty's instructions here: https://github.com/keatontaylor/alexa_media_player/issues/258#issuecomment-515758424

**Comment by petestanley112** [comment]
Not sure about unraid. But mine is installed on esxi with a ubuntu instance. And I have it working. Well tts anyhow. 

The pickle file is in/config file same place as configuration.yaml file. It only shows once you complete the capture popup. Took me a few trays to get it working. Mostly down to errors in automations and scripts files not the plugin discussed here

**Comment by 3ative** [comment]
@petestanley112 
What trays did you use? - I haven't needed any myself.

**Comment by mattnewham** [comment]
OK, so ran the shell script, all fine (I had removed the configurator plugin as I use git to manage my config files).

There is no pickle file in my config dir though. Only one for my Ring doorbell. AlexaPY was working fine until the other day when this change became apparent, so I've already set up the connection to Amazon, so confused as to why I dont have a .pickle file?

**Comment by petestanley112** [comment]
Trays? Not sure I follow. I have moved from open hab, trying to forget that and come to .yaml files has been quite a learning curve

**Comment by 3ative** [comment]
@petestanley112 
You mentioned: "Took me a few trays to get it working."

@mattnewham 
Did you get it working again?

**Comment by mattnewham** [comment]
@3ative yep - not sure how though. I just restarted my instance and its working again now. I guess I was still properly authenticated because I didnt have to do any authentication steps, just started working when I put the new alexapy in the config dir. Should it not really go into deps though? I dont really like it in the root of the config dir

**Comment by 3ative** [comment]
@mattnewham 
Cool, glad to hear it.
Same here, I didn't need any re-authentication either - even after deleting the .pickle file. 
I know what you mean, my OCD hates the new folders/files in the Root too. :)

**Comment by leonka93** [comment]
Hi I followed your instructions, but continue to give me the same problem. in config the alexapy folder appeared, should I put it under custom_component? thanks i'm a noob.

**Comment by petestanley112** [comment]
God knows how to send messsges@ some one. 

But yeah took a few trays to get it working del picke reinstalled the

**Comment by 3ative** [comment]
@petestanley112 
I'm still not sure what trays you are using. LOL

**Comment by petestanley112** [comment]
@3ative 
Sorry I realise now it was a typo. I'm dyslexic I tend to read exactly as written and cant see past it sometimes..............

 oh I have just seen it...... I'm on my phone bloody auto correct... lol

**Comment by 3ative** [comment]
@petestanley112 
**LMAO** - _I get it now_, I thought I was missing something. :)

**Comment by 3ative** [comment]
@leonka93 
Running the script put these two folders in the Root of my Config folder
![Capture](https://user-images.githubusercontent.com/51385971/62403674-ee505d00-b586-11e9-88d1-ec35a2e46a61.JPG)
I haven't and didn't need to move them.

**Comment by mattnewham** [comment]
Did you restart homeassistant ? And delete the Alexa media pickle file from
/config?

**Comment by leonka93** [comment]
@ 3ative@mattnewham yes I deleted the pickle file and restart HA. but after the reboot the pickle file continues to appear, and it does not find me nor the Alexa speakers associated with my account asks me to verify it

**Comment by leonka93** [comment]
I installed hassio on Raspberry Pi 3+.The URL is amazon.it thanks to all

**Comment by 3ative** [comment]
@leonka93 
That .pickle file [should] return - post restart.
Not sure about your other issues, I've not had any trouble with my setup, soz I can't help futher.

**Comment by alandtse** [comment]
> can you point me I to the direction where I can resolve my problems I have now. Thanks

Please search or start a new issue. The goal is to make it easy for people to find the solution for their problem. Having someone ask about something completely different and extending this thread makes that difficult.

**Comment by leonka93** [comment]
after a few reboots, finally work, the pickle file continues to appear but does not create problems for music playback. I do some tests for notifications etc. I'll update you. thanks

**Comment by keatontaylor** [comment]
> It looks like Amazon have tweaked the API, and the AlexaPy library no longer gets the CSRF token from the login URL (and there's no error checking in the **init** function there).
> 
> Given the upstream maintainers lack of time, I've forked the AlexaPy repo and updated the site - I'd raise a PR but it's a one line change and I've not done anything to actually test it - but it works for me.
> 
> You can find the updated repo at https://gitlab.com/jfautley/alexapy - I've tested this against an Amazon UK account using Hass.IO.
> 
> To install (on Hass.IO), SSH into your instance and run:
> `pip3 install --target /config --no-dependencies git+https://gitlab.com/jfautley/alexapy`
> 
> For other Home-Assistant installs, you should be able to use `--target /path/to/config/deps` but for some reason the PYTHONPATH on Hass.IO is messed up... 🤷‍♂

Please make a PR on the gitlab page.

**Comment by alandtse** [comment]
@keatontaylor I'm actually reviewing if we can make a more robust fix so we can feed multiple urls to iterate through.

**Comment by alandtse** [comment]
As an update, there's a new OTP page where you can then select voice or SMS which we need to handle particularly if you have multiple devices. Looking at a solution now.

**Comment by rjbrookes** [comment]
Hi I am new to all this and have very limited knowledge.  Trying to get the Alexa devices shown on media players, when I open the configurator - execute shell command and copy the above mentioned pip3 line it fails to update... I get this:


Command executed: pip3 install --target /config --no-dependencies git+https://gitlab.com/jfautley/alexapy: 1
Collecting git+https://gitlab.com/jfautley/alexapy
  Cloning https://gitlab.com/jfautley/alexapy to /tmp/pip-req-build-tt6qrcya
  Running command git clone -q https://gitlab.com/jfautley/alexapy /tmp/pip-req-build-tt6qrcya
  fatal: unable to access 'https://gitlab.com/jfautley/alexapy/': Could not resolve host: gitlab.com
ERROR: Command "git clone -q https://gitlab.com/jfautley/alexapy /tmp/pip-req-build-tt6qrcya" failed with error code 128 in None

any ideas... spent all day trying to get Alexa to work!

thanks in advanced.

**Comment by DrBeaker73** [comment]
I dont normally post, but I have to say a HUGE thank you to @jfautley for finding this fix and to @fogarty  for making the fix easy. I've spread the word where I can!

**Comment by cubilon** [comment]
Thanks to @fogarty for the solution! Not clear to me how to fix it on Home Assistant on wheels@Buster. 

pip3 install --target /config --no-dependencies git+https://gitlab.com/jfautley/alexapy

This is the command for HASSIO, but how to solve on buster?

**Comment by Sk4zz** [comment]
Also thanks to @fogarty for the fix. I'm running hassbian and installed the fix by changing to homeassistant's virtualenv:

`source /srv/homeassistant/bin/activate`

the path might be different, if you installed homeassistant manually on a buster system. And then installed the fix to my local homeassistant/<config> via

`pip3 install --target /home/homeassistant/.homeassistant/ --no-dependencies git+https://gitlab.com/jfautley/alexapy`

You might need to run this command as root if your user hasn't write access to the homeassistant's config dir.

After applying this patch, I have media_player instances for my echos available. Unfortunately, they don't work and my journal shows approximately every 10secs the following error messages.

```
Aug 06 21:47:37 hassbian hass[3408]: 2019-08-06 21:47:37 ERROR (MainThread) homeassistant.helpers.entity] Update for media_player.this_device fails
Aug 06 21:47:37 hassbian hass[3408]: Traceback (most recent call last):
Aug 06 21:47:37 hassbian hass[3408]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
Aug 06 21:47:37 hassbian hass[3408]:     await self.async_device_update()
Aug 06 21:47:37 hassbian hass[3408]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 380, in async_device_update
Aug 06 21:47:37 hassbian hass[3408]:     await self.hass.async_add_executor_job(self.update)
Aug 06 21:47:37 hassbian hass[3408]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Aug 06 21:47:37 hassbian hass[3408]:     result = self.fn(*self.args, **self.kwargs)
Aug 06 21:47:37 hassbian hass[3408]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 428, in update
Aug 06 21:47:37 hassbian hass[3408]:     no_throttle=True)
Aug 06 21:47:37 hassbian hass[3408]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
Aug 06 21:47:37 hassbian hass[3408]:     result = method(*args, **kwargs)
Aug 06 21:47:37 hassbian hass[3408]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
Aug 06 21:47:37 hassbian hass[3408]:     result = method(*args, **kwargs)
Aug 06 21:47:37 hassbian hass[3408]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 256, in refresh
Aug 06 21:47:37 hassbian hass[3408]:     self._last_called = self._get_last_called()
Aug 06 21:47:37 hassbian hass[3408]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 357, in _get_last_called
Aug 06 21:47:37 hassbian hass[3408]:     ['serialNumber']))
Aug 06 21:47:37 hassbian hass[3408]: TypeError: 'NoneType' object is not subscriptable
```
I would appreciate it, if you could point me in the right direction.
