### ISSUE TITLE
The following components and platforms could not be set up:  alexa_media.media_player @0.97b0

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa_media_player#259]
**Describe the bug**
The following components and platforms could not be set up:
alexa_media.media_player

Log Details (ERROR)
Unable to prepare setup for platform alexa_media.media_player: Platform not found (cannot import name 'MEDIA_PLAYER_SCHEMA' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)).

**To Reproduce**

Install recent beta and you will see.

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.97.0b0
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 1.3.1
 - alexapy (version from `pip show alexapy` or HA startup): 0.7.0

**Additional context**
Ludeeus meant : Custom components should provide a const.py file in the integration dir, that way when consts change in core, they will not break.

Aka it looks like the const was renamed I guess?
Here we are: https://github.com/home-assistant/home-assistant/commit/f1e4153b2c4a9e18eebb037d2332c76f1a625c97#diff-5611ccdb60e42595186058f82df9c7a8

**Comment by niemyjski** [comment]
I'm also running into this.

**Comment by arcangelweb** [comment]
I can also confirm the issue

**Comment by arcangelweb** [comment]
at 0.97b1, the complement continues to work.

**Comment by niemyjski** [comment]
Fails to work for me

**Comment by alandtse** [comment]
Fix in queue, please test.

**Comment by dreimer1986** [comment]
Tested, my Alexa speaks again :D Media Players are back too. FIXED

**Comment by arcangelweb** [comment]
The component loads and seems to work correctly

**Comment by alandtse** [comment]
Thanks. I'll plan to release something tonight. Still have one other bug to fix.

**Comment by Kanga-Who** [comment]
@alandtse Updated to 0.97.0 this morning, and found this error.

Checked for an update to the components in HACS, no update available. Anyone updating to 0.97.0 will have this issue and most likely spam the forums about it.

I made the changes from above, and the issue is resolved. When will the update be pushed to HACS?

**Comment by alandtse** [comment]
Hopefully tonight.

**Comment by DeviousPenguin** [comment]
I've just gone from HA 0.96.5 to 0.97.0 stable and am also getting this issue.

I guess I should wait until 0.97.1 for a fix? Or is it the custom component that needs to be updated instead?

Anyway a simple workaround that worked for me is to go back to 0.96.5

**Comment by pixeye33** [comment]
@alandtse with 1.4.0 installed on 0.97.0 i've got this : 
`ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.media_player: Platform not found (cannot import name 'MEDIA_PLAYER_SCHEMA' from 'homeassistant.components.media_player' (/usr/src/app/homeassistant/components/media_player/__init__.py)).`
Might not be fixed really ?
