### ISSUE TITLE
Connection pool is full, discarding connection.. Tons of connections to amazons cloud

### ISSUE THREAD

**Issue by niemyjski** [keatontaylor/alexa_media_player#264]
I'm running hassio 0.97.0b2 and for the past 2 months I've had a very flakey ui where ui stops updating but ssh and all sensors are working. I occasionally get sensors failed to update in x time. I have a ton of local integrations and very few remote integrations. I noticed the following in my logs this morning..

```2019-08-05 11:27:00 WARNING (SyncWorker_10) [urllib3.connectionpool] Connection pool is full, discarding connection```

I then went and got a list of all connections inside of the docker container after I killed a ton of integrations and I see this: https://cinhtau.net/2018/09/14/check-connections-for-docker-container/

I'm seeing a ton (I mean a ton) of connections to `13.33.155.x` which is cloud front/amazon. I was curious if you use connection pooling or limit the number of requests you make? For reference I have at least 25 Alexa devices (1-2 per room).

**Comment by alandtse** [comment]
We should only enable a single persistent websocket connection per Alexa account and then we create individual http connections for commands or updates.  Those individual connections should be getting closed automatically by the OS.  Can you confirm it's coming from this component as opposed to the built in component?

It's mentioning SyncWorker_10, can you see what component is using that Sync_Worker?

**Comment by alandtse** [comment]
You may be right, I have 5 and I see 5 https connections in various tcp states.
```
tcp       32      0 raspberrypi:34876       ec2-52-4-59-219.c:https CLOSE_WAIT
tcp        0      0 raspberrypi:48618       ec2-3-220-156-246:https ESTABLISHED
tcp        0      0 raspberrypi:53292       ec2-52-25-100-175:https TIME_WAIT
tcp        0      0 raspberrypi:45472       ec2-52-0-76-124.c:https ESTABLISHED
tcp        0      0 raspberrypi:57162       ec2-52-72-221-205:https TIME_WAIT
```

**Comment by niemyjski** [comment]
I’m not sure how I’d confirm that but I disabled the integration and 99% of them went away

**Comment by niemyjski** [comment]
Almost most of mine were in the established state if I remember correctly

**Comment by alandtse** [comment]
0.2.0 is available on HACS and uses a whole different connection library (requests -> aiohttp). I'll close this since it likely isn't relevant anymore. Please open a new one if this comes back.

**Comment by niemyjski** [comment]
Thanks!
