### ISSUE TITLE
Unable to install all requirements: alexapy==0.7.1

### ISSUE THREAD

**Issue by Kanga-Who** [keatontaylor/alexa_media_player#275]
I updated my parents HA running on a Pi3 with Hass.io over Raspbian, to 0.97.0 today, and `alexa_media` to 1.4.0/1, and am now receiving this error message.

`Unable to install all requirements: alexapy==0.7.1`

I have a NUC running the exact same versioning, in my house and have no issue, so I can't figure out what the issue maybe? Seems to be something to do with Alpine being used now?

`2019-08-09 15:12:08 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package alexapy==0.7.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595a90>: Failed to establish a new connection: [Errno -3] Try again')': /simple/alexapy/

  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595970>: Failed to establish a new connection: [Errno -3] Try again')': /simple/alexapy/

  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x755959d0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/alexapy/

  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595930>: Failed to establish a new connection: [Errno -3] Try again')': /simple/alexapy/

  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595890>: Failed to establish a new connection: [Errno -3] Try again')': /simple/alexapy/

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595550>: Failed to establish a new connection: [Errno -3] Try again')': /alpine-3.10/armv7/

  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595470>: Failed to establish a new connection: [Errno -3] Try again')': /alpine-3.10/armv7/

  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x755954f0>: Failed to establish a new connection: [Errno -3] Try again')': /alpine-3.10/armv7/

  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x755953b0>: Failed to establish a new connection: [Errno -3] Try again')': /alpine-3.10/armv7/

  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x75595350>: Failed to establish a new connection: [Errno -3] Try again')': /alpine-3.10/armv7/

  ERROR: Could not find a version that satisfies the requirement alexapy==0.7.0 (from versions: none)

ERROR: No matching distribution found for alexapy==0.7.0

2019-08-09 15:12:08 ERROR (MainThread) [homeassistant.requirements] Not initializing alexa_media because could not install requirement alexapy==0.7.0`

**Comment by alandtse** [comment]
The error logs you have below appears to be for an older version since it's requesting 0.7.0 and not 0.7.1. Regardless, I'm not sure why alpine doesn't have the same [alexapy library](https://pypi.org/project/AlexaPy/) availability.
The log is showing a connection error. Perhaps restart the device?

**Comment by Kanga-Who** [comment]
I had downgraded to try and see if that would fix the problem. The same errors were showing 0.7.1, apologies for the confusion with the title.

RPi3 rebooted, Hass.io completely wiped and reinstalled, all alexa_media files deleted, pickle deleted, the issue still persists.

**Comment by alandtse** [comment]
Don't wipe between reboots. Hass.io has always had a weird problem updating custom_components dependencies in the first few runs.

Someone posted this before (I slightly modded it just now) and if it works should probably go in the wiki.

> the simplest way would be to go to the "Configurator" then clic on settings and on "Execute shell Command"
> Paste here the command:
> `pip3 install --target /config --no-dependencies alexapy==0.7.1`
> 
That would install the dependency in the config directory, which mean it'll override the system. It could leave you with incompatible versions.  I'd suggest the simpler command.
`pip3 install alexapy==0.7.1`

**Comment by Kanga-Who** [comment]
> I'd suggest the simpler command.
pip3 install alexapy==0.7.1

I had tried this before posting but Docker didn't want to install it.

I ahd tried numerous reboots in between before wiping and starting again. I was just trying to get to the point of everything I had done.

It's strange as I have a NUC with Hass.io installed the exact same way using this script.
`curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s` and all is working perfectly,

Using the same script and the same config files on a RPi3 gives the issue.

**Comment by Kanga-Who** [comment]
So, turns out, PiHole was stopping it from working.

I just turned PiHole off, rebooted, and everything came back online. Very strange as PiHole has been running previously and the issue has not occurred.

PiHole also running on my NUC, updated and runs without error. Weird...

**Comment by alandtse** [comment]
Ok glad you resolved it. I'll close this out.
