### ISSUE TITLE
0.97.0 HASS.IO seems to break Media Player

### ISSUE THREAD

**Issue by G8YTZ** [keatontaylor/alexa_media_player#278]
Updating HASS.IO to 0.97 (from 0.95.4) has broken the Lovelace Media Player inserts (Not sure about TTS as I am away from home for another week right now). The error is: 

Log Details (ERROR)
Fri Aug 09 2019 23:15:20 GMT+0100 (IST)

Unable to prepare setup for platform alexa_media.media_player: Platform not found (cannot import name 'MEDIA_PLAYER_SCHEMA' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)).
Connection lost. Reconnecting…

I'd much appreciate any advice here, the component is  most useful.

**Comment by alandtse** [comment]
This is a known issue #259 and already fixed.  Update to the latest version 1.4.1.
