### ISSUE TITLE
Node-RED Support Example

### ISSUE THREAD

**Issue by jlvandusen** [keatontaylor/alexa_media_player#279]
**Is your feature request related to a problem? Please describe.**
Ability to continue using Node-RED for automations involving Alexa... need a few examples to show the new syntax... before latest version was able to supply a DATA node and populate with the following format:
msg.payload = 
{
"message":"test",
"data":{"type":"tts"},
}
return msg;

then just add a call service node and populate with tts and the service alexa_media and then the entity_id of media_player....echo device.

That sent whatever was in the data to the echo.  It also allowed me to begin using replace and variables to send context statements based on the event that called data.

How do we do this now today?

**Describe the solution you'd like**
Just some quick examples if you use Node-RED of how to call the Alexa_media either TTS or Announce and maybe how you would replace variables (title etc) so I can convert my stuff.

**Describe alternatives you've considered**
Just a quick example of either allowing me to fix my existing flows.

**Additional context**
Hoping the above makes sense... this is great work you are doing!

**Comment by alandtse** [comment]
Please refer to the wiki on the notification component or review the HA thread as people have recently posted their node_red examples.

**Comment by jlvandusen** [comment]
Thank you - Which HA thread are you referring to?

**Comment by alandtse** [comment]
Yes.
