### ISSUE TITLE
Cannot add repo via HACS

### ISSUE THREAD

**Issue by antoniodowling** [keatontaylor/alexa_media_player#284]
**Describe the bug**
When adding via HACS, the following error occurs:

```
19-08-13 02:37:55 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/keatontaylor/alexa_media_player repository

19-08-13 02:37:56 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/9f69aead/repository.json: [Errno 2] No such file or directory: '/data/addons/git/9f69aead/repository.json'

19-08-13 02:37:56 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/9f69aead/repository.json
```

**To Reproduce**
1. Attempt to add the URL https://github.com/keatontaylor/alexa_media_player to HACS.

**Expected behavior**
The repo is added (and becomes searchable, etc.) without issue.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 173
 - Hassio (Yes/No): Yes.
 - alexa_media  (version from `const.py` or HA startup): N/A
 - alexapy (version from `pip show alexapy` or HA startup): N/A

**Additional context**
This HA issue seems to be similar, so maybe the solution is to update the repository.json file?

https://github.com/home-assistant/hassio/issues/909

**Comment by alandtse** [comment]
That is not HACS and is not supported. https://github.com/custom-components/hacs
