### ISSUE TITLE
How to notify specific Alexa mobile apps

### ISSUE THREAD

**Issue by MYeager1967** [keatontaylor/alexa_media_player#286]
I have two entities named as follows:

media_player.mike_s_alexa_apps
media_player.laurie_s_alexa_apps

and I'm able to send notifications to them. Problem is, they both go to my phone. I need to know how to make it so that I can send notifications to both phones. Here's the code that sends the notification:

  - data_template:
      data:
        type: push
      message: Pool Temp - {{states.sensor.pool_temp.state}}     DHW Temp - {{states.sensor.dhw_temp_215.state}}
      target:
      - media_player.mike_s_alexa_apps
      - media_player.laurie_s_alexa_apps
      title: Home Assistant
    service: notify.alexa_media

Any suggestions???

**Comment by alandtse** [comment]
Push doesn't use target like that. It sends to all apps on the same Alexa account. You can specify individual Alexa accounts using target.

This is an Amazon limitation. You can see it by setting up a test routine in the app.

**Comment by MYeager1967** [comment]
So if my phone is on my account and hers is on her account, how would I specify the target? I tried it with both phone apps on the same account and it didn't work but I was using the same configuration so that was likely the problem...

**Comment by alandtse** [comment]
You need to set up both accounts in HA. Makes sure to exclude her mobile app from your account and exclude any shared echo devices between the accounts so they don't get double created (unless you want them).  Check the Wiki for details on exclude_devices.  Then you should be able to target the mobile app since it will be sending the push through her account.

**Comment by MYeager1967** [comment]
Ok, I tried to add a second account and wound up with a corrupt pickle file. I deleted it and reverted back to my previous configuration. Deleted the pickle file (should have just renamed it to start with) and went through the captcha thing again. Looks good but no devices like I had before...

Here's the error I'm getting now:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 93, in setup_platform
    hass)
  File "/config/custom_components/alexa_media/media_player.py", line 115, in __init__
    self.alexa_api = AlexaAPI(self, login)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 51, in __init__
    csrf = self._session.cookies.get_dict()['csrf']
KeyError: 'csrf'

Why is it I always get myself into these things? :-)

**Comment by MYeager1967** [comment]
After reverting back to the newest version of the program, I get all the switches for DND, Repeat, and whatever, but the log is full of entries like:

2019-08-14 22:10:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 216, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name))
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Bedroom Dot shuffle switch
2019-08-14 22:10:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 216, in async_update_ha_state
    "No entity id specified for entity {}".format(self.name))
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Laurie's Alexa Apps do not disturb switch

All the switches are there and they appear to work (at least the DND ones do), I just get this error. Any ideas on how to get rid of the error? Obviously this is secondary to trying to get the wifes phone working with the Alexa notifications....

**Comment by alandtse** [comment]
There is an open thread about the NoEntitySpecified Error, it will be fixed eventually as it's harmless.

Are you saying you can't get the notification running with the separate accounts? If you want to try to debug using a single account for both, we'll need you to get us the [routine info](https://github.com/keatontaylor/alexa_media_player/wiki/Sequence-Discovery) if you create a routine that actually works. Since we'd need the entire json, just follow the instructions to step 7 and then copy the entire operation payload in here (scrub as necessary).

**Comment by MYeager1967** [comment]
I was unable to get the second account added. At the moment, I simply have her Alexa app logged in with my info and it works just fine. We really don't use the app so it's really just running to catch the notifications. I figured the errors were fairly meaningless as everything was there and working, I just wasn't sure.

**Comment by alandtse** [comment]
Ok, I'll close this since you have a workaround.

**Comment by MYeager1967** [comment]
Thanks. Excellent component!
