### ISSUE TITLE
TypeError: login() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by Senbei123** [keatontaylor/alexa_media_player#287]
Hi all,

I try to setup the component the second time. First time month ago it works perfect, nowadays I got some issue.

First of all I install the component with HACS. Then I set up the necessary lines in configuration.yaml file. Now the captcha pops up. BUT after entering the numbers/caracters and push confirm nothing happend.

I checked the home assistant log and get the following result each time when I push the CONFIRM button:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/alexa_media/__init__.py", line 123, in setup_platform_callback
>     login.login(data=callback_data)
> TypeError: login() got an unexpected keyword argument 'data'`

Any comment how to fix or continue?

Many thanks in advance.

Br, Tristan

**Comment by alandtse** [comment]
Please ensure you're not using a custom version of alexapy. If you followed any workarounds to install it in your configuration directory, you will get this error as you will have an outdated library.

**Comment by Senbei123** [comment]
Thanks - I though I already delete anything but find an additional alexapy file. After deleting and reinstall this component every alexa device got found. Many thanks!
