### ISSUE TITLE
Do not disturb does not update when activated manually or through the app

### ISSUE THREAD

**Issue by MYeager1967** [keatontaylor/alexa_media_player#288]
I have an Echo Show (the large one if it makes any difference) and with the newest version of the media player, I gained a 'Do Not Disturb' switch. If I use the switch, the device goes in and out of DND. However, if the DND mode is activated at the device itself, the switch does not follow that action. I don't know if this is a bug or if it's possible to keep it in sync, so I'm just putting it out there.

Wonderful component and I use the hell out of it. The inclusion in HACS is also great as it will make keeping it up to date much easier. Now if they'd just get things working correctly again with Vera so I could stay current. Looks like I'm trapped on 94.4 at the moment to maintain the wife acceptance factor...

**Comment by alandtse** [comment]
Unfortunately we don't have a way to track if it changes in the app or hardware. We can track voice commands though.

**Comment by MYeager1967** [comment]
That's cool. I just wondered if it had gotten overlooked. 😀
