### ISSUE TITLE
Feature Request: Have feedback from Echo to HA once the TTS accouncement has finished.

### ISSUE THREAD

**Issue by DeviousPenguin** [keatontaylor/alexa_media_player#290]
It would be nice if there was some feedback from the Echo device once it has finished it's TTS accouncement. 

I currently have another non-echo media player, and I have my automation so it turns down the volume of my non-echo media player so I can hear the TTS from the Echo.

After 10 seconds I have the volume of my non-echo media player go back to it's original volume, but with long TTS announcements my non-echo media player is then too loud to hear the end of the TTS announcement. If there was some sort of feedback I could get rid of the 10 second delay and have the volume change back as soon as the TTS is finished.

Maybe the status of the Alexa devices could change during TTS announcements? Currently my Echo's show as 'standby' state before,  during and after TTS announcements.

**Comment by alandtse** [comment]
Unfortunately, this is not possible as the Amazon API does not provide any status on TTS or Announce.

Feel free to reopen if some other implementation figures out a way to determine this.

**Comment by DeviousPenguin** [comment]
Ok, thanks for letting me know. Hopefully they may add this feature to the API in future :)

**Comment by eugeneniemand** [comment]
I was looking for exactly the same feature and found this thread. I was hoping that the status will change to TTS then back to playing or something like that
