### ISSUE TITLE
Media Player Source

### ISSUE THREAD

**Issue by broyuken** [keatontaylor/alexa_media_player#300]
When clicking the source button on a media player entity it only shows local speaker, not all of the Alexa devices on my account.

**Comment by alandtse** [comment]
Not a bug. That's for Bluetooth source selection. If you are missing Bluetooth devices please let us know.

**Comment by broyuken** [comment]
Could we add this as a feature request then?

**Comment by alandtse** [comment]
No. The current HA architecture is that each Alexa is it's own media player. If you want to control other devices, use the appropriate media player.
