### ISSUE TITLE
Alexa problem whit amazon.de

### ISSUE THREAD

**Issue by Ghostsl84** [keatontaylor/alexa_media_player#301]
Excuse me my english is not the best :-)

i have a problem white the integration over HACS- Alexa Media Player 2.0.0

i have my configuration.yaml modifyied with this

Alexa
alexa_media:
accounts:
- email: xxxxxxxatxxxxx.de
password: XXXXXXX
url: amazon.com

and capache maked

and i change the URL in:

url: amazon.de and i have confirme
and restart.

my Alexa devices have the state: No state available for media_player.alexa

installed over HACS - Home Assistant version 0.97.2

edit: and i have a problem with this
setup of alexa_media is taking over 10 seconds.

Thanks
Ghosty

**Comment by dreimer1986** [comment]
Another german here. This is how it works here:

alexa_media:
  accounts:
    - email: a.b@c.de
      password: "password"
      url: amazon.de

**Comment by Ghostsl84** [comment]
Hello

my Alexa devices registered in Germany

i have this in my configuration.yaml

alexa_media:
  accounts:
    - email: a.b@c.de
      password: "password"
      url: amazon.de

and Home Assistant says - 

Alexa Media Player - Begin - email at email.de
Please hit confirm to begin login attempt.
"Confirm"

and I click on Confirm again and again and it does not work

Thanks for your help

**Comment by Ghostsl84** [comment]
I did but it does not work
still the same as in this video 
https://github.com/keatontaylor/alexa_media_player/issues/307#issue-485842255

Thanks

**Comment by alandtse** [comment]
Ok, the workaround is described in #307 to downgrade to 1.4.1 login, and then upgrade to 2.0.0. I'll continue debugging in that thread since it has a video to reference.

**Comment by Ghostsl84** [comment]
many thanks for the help.
I managed to connect to Alexa.
All automations, scripts etc .. are available and can be controlled with Alexa.
Home assistant does not find Alexa-Media version 1.4.1
I have the alexa_media_player-master from 22.09.2019 in HASSIO \ config \ custom_components \ alexa_media but he has no connection with Amazon.de.
As soon as I switch to Amazon.com I get Alexa but they are all "Not Available"
I change it again to amazon.de I get told Alexa-media not found. (All under 1.4.1)
