### ISSUE TITLE
Passing commands to Alexa

### ISSUE THREAD

**Issue by dreimer1986** [keatontaylor/alexa_media_player#46]
Some ppl here complained about Alexa handling their TTS requests as speech command like "Alexa switch light x on". I'd like to actively use this in my case to run my custom skill doing stuff. Background is I want Alexa to say something when I need it to, but more as question where I can reply to and the reply triggers something. Example is I enter the home zone and get a "Welcome home, do you want your PC being switched on?" "Yeah/Nope" and it passes my answer to Home Assistant doin specific stuff. TTS does not allow that but passing my skill a secific command I can realize such behavior. Can this "mis"-behavior be added as a feature maybe?

**Comment by alandtse** [comment]
Other then regions where TTS was broken, does anyone know of an implementation that does this? I can't seem to find anyone able to do this to try to replicate it.

**Comment by alandtse** [comment]
I'll close this for now since I think we're stuck without some use cases.

**Comment by dreimer1986** [comment]
Seems like this works now. Thx very much for adding such feature ^^ Coffee was spent

**Comment by alandtse** [comment]
Check out if https://github.com/custom-components/alexa_media_player/wiki#run-custom-command allows this now.
