### ISSUE TITLE
Fix selection of locale to be based on user

### ISSUE THREAD

**Issue by alandtse** [keatontaylor/alexa_media_player#79]
Currently, we hardcode EN-US as the locale for much of the selection. It appears to cause no issues so far, but it may in the future.

Spawned from #74 where umlauts were not processed correctly by Amazon.

**Comment by alandtse** [comment]
The big question is does Amazon provide any reliable endpoint to show the locale. Otherwise we may have to hard code a list of locales based on the login domain.

**Comment by keatontaylor** [comment]
I don't see a good solution for this. Any API endpoints where we could get the users locale would still require us to login with a default locale and be subject to the same issues if amazon at any point starts enforcing the locale to be correct. 

With that said it might only make sense to build a map of locales based on the URL provided by the user. I don't believe this will change, but I could be wrong, please chime in with feedback @alandtse

**Comment by alandtse** [comment]
I think the locale for login may not matter since we haven't seen any errors that seem tied to that yet. There is actually a variable that could be replaced in routines with the appropriate device specific locale found from [device preferences](https://alexa.amazon.com/api/device-preferences).
```
"locale":"ALEXA_CURRENT_LOCALE"
```
Currently, we don't do any replacement of this value, but we probably should at some point.
